# Generated by Django 6.0.3 on 2026-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('category', models.CharField(choices=[('food', 'Еда'), ('transport', 'Транспорт'), ('fun', 'Развлечения'), ('education', 'Образование'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
    ]
